export const GET_USERS = "GET_USERS";
export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const GET_TEAM_MEMBERS = "GET_TEAM_MEMBERS";
export const GET_TEAM_MEMBER = "GET_TEAM_MEMBER";
export const UPDATE_TEAM_MEMBER = "UPDATE_TEAM_MEMBER";

export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const ADD_CLIENT = "ADD_CLIENT";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT = "GET_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const RECOVER_EMAIL_SENT = "RECOVER_EMAIL_SENT";
export const RECOVER_EMAIL_ERROR = "RECOVER_EMAIL_ERROR";
export const GET_GREENINVOICE_TOKEN = "GET_GREENINVOICE_TOKEN";

export const GET_PRESETS = "GET_PRESETS";
export const GET_ALERTS = "GET_ALERTS";

export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";

export const GET_EXPENSES = "GET_EXPENSES";
export const GET_EXPENSE = "GET_EXPENSE";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";

export const GET_PAYMENTS = "GET_PAYMENTS";
export const GET_PAYMENT = "GET_PAYMENT";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";
